CREATE TABLE SHOOL_STUDENTS (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(20) NOT NULL,
	LASTNAME VARCHAR(20) NOT NULL,
	GENDER CHAR(1) NOT NULL,
	BIRTHDATE DATE NOT NULL,
	AVG DOUBLE,
	MIN_VOTE DOUBLE,
	MAX_VOTE DOUBLE,
); 