/*DDL*/
DROP TABLE utenti;

CREATE TABLE IF NOT EXISTS utenti(
	id  serial NOT NULL PRIMARY KEY,
	NOME VARCHAR NOT NULL,
	COGNOME VARCHAR NOT NULL,
	CITTA_ID INT8 NOT NULL,
	NOTE TEXT,

	CONSTRAINT UTENTI_CITTA_FK FOREIGN KEY (CITTA_ID) REFERENCES CITTA(ID_CITTA)
);

CREATE TABLE IF NOT EXISTS CITTA(
	ID_CITTA serial NOT NULL PRIMARY KEY
);



ALTER TABLE UTENTI ADD CF varchar(16) NOT NULL UNIQUE;